"""Explicit CMS allowlist. Sensitive fields are never inferred from a request."""

from app import models as m

# key: model, permission prefix, editable fields. Empty fields means read-only.
CONTENT = [
    "title",
    "slug",
    "short_description",
    "description",
    "cover_image",
    "published",
    "is_demo",
    "seo_title",
    "seo_description",
    "keywords",
]
REGISTRY = {
    "pages": (m.Page, "page", CONTENT),
    "sections": (m.PageSection, "page", ["page_id", "title", "content", "position"]),
    "menus": (m.NavigationItem, "page", ["title", "path", "position", "published"]),
    "projects": (
        m.Project,
        "project",
        CONTENT
        + [
            "category_id",
            "location",
            "start_date",
            "end_date",
            "status",
            "beneficiary_count",
            "target",
            "progress",
            "objectives",
            "activities",
            "outcomes",
            "impact",
            "video",
            "featured",
        ],
    ),
    "project-categories": (m.ProjectCategory, "project", ["title"]),
    "project-images": (
        m.ProjectImage,
        "project",
        ["project_id", "media_id", "caption", "position"],
    ),
    "artisans": (
        m.Artisan,
        "artisan",
        CONTENT
        + [
            "category_id",
            "location",
            "skill",
            "craft",
            "experience",
            "products",
            "social_url",
        ],
    ),
    "artisan-categories": (m.ArtisanCategory, "artisan", ["title"]),
    "events": (
        m.Event,
        "event",
        CONTENT
        + [
            "location",
            "date",
            "start_time",
            "end_time",
            "registration_enabled",
            "registration_limit",
            "organizer",
            "status",
        ],
    ),
    "registrations": (m.EventRegistration, "event", []),
    "volunteers": (m.VolunteerApplication, "volunteer", []),
    "donations": (m.Donation, "donation", []),
    "receipts": (m.DonationReceipt, "donation", []),
    "contacts": (m.ContactMessage, "contact", []),
    "subscribers": (m.NewsletterSubscriber, "subscriber", []),
    "blog": (m.BlogPost, "blog", CONTENT + ["author", "category_id", "publish_date"]),
    "blog-categories": (m.BlogCategory, "blog", ["title"]),
    "blog-tags": (m.BlogTag, "blog", ["title"]),
    "gallery": (
        m.Gallery,
        "media",
        CONTENT + ["category", "media_id", "artisan_id", "event_id", "location"],
    ),
    "media": (m.MediaAsset, "media", ["title", "tags", "alt_text", "folder"]),
    "documents": (
        m.Document,
        "document",
        [
            "title",
            "category",
            "year",
            "description",
            "media_id",
            "project_id",
            "visibility",
        ],
    ),
    "statistics": (
        m.ImpactStatistic,
        "impact",
        ["title", "value", "verified", "position"],
    ),
    "stories": (m.ImpactStory, "impact", CONTENT + ["date_label", "position"]),
    "social": (m.SocialLink, "settings", ["title", "url"]),
    "faq": (m.FAQ, "page", ["question", "answer", "position", "published"]),
    "users": (m.User, "user", ["name", "email", "role_id", "active"]),
    "roles": (m.Role, "role", ["name"]),
    "permissions": (m.Permission, "role", []),
    "audit": (m.AuditLog, "audit", []),
}

# Only these columns appear in operations tables and CSV exports.
PRIVATE_COLUMNS = {
    "volunteers": [
        "id",
        "name",
        "email",
        "phone",
        "city",
        "age",
        "occupation",
        "skills",
        "availability",
        "areas_of_interest",
        "message",
        "consent",
        "status",
        "created_at",
    ],
    "contacts": [
        "id",
        "name",
        "email",
        "phone",
        "subject",
        "message",
        "status",
        "created_at",
    ],
    "subscribers": ["id", "name", "email", "consent", "created_at"],
    "registrations": [
        "id",
        "event_id",
        "name",
        "email",
        "phone",
        "status",
        "created_at",
    ],
    "donations": [
        "id",
        "name",
        "email",
        "amount",
        "currency",
        "status",
        "order_id",
        "payment_id",
        "payment_method",
        "created_at",
    ],
    "receipts": ["id", "donation_id", "receipt_number", "created_at"],
    "audit": ["id", "user_id", "action", "entity", "entity_id", "ip", "created_at"],
    "permissions": ["id", "name"],
}
