"""Initial relational schema

Revision ID: b771f698010d
Revises: 
Create Date: 2026-09-19 15:05:18.149729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b771f698010d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artisan_category',
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('artisan_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artisan_category_created_at'), ['created_at'], unique=False)

    op.create_table('blog_category',
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('blog_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_category_created_at'), ['created_at'], unique=False)

    op.create_table('blog_tag',
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('blog_tag', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_tag_created_at'), ['created_at'], unique=False)

    op.create_table('contact_message',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('subject', sa.String(length=180), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_contact_message_created_at'), ['created_at'], unique=False)

    op.create_table('donation',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('pan_encrypted', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('anonymous', sa.Boolean(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('purpose', sa.String(length=180), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('order_id', sa.String(length=100), nullable=True),
    sa.Column('payment_id', sa.String(length=100), nullable=True),
    sa.Column('signature', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('payment_method', sa.String(length=40), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('amount >= 100'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id'),
    sa.UniqueConstraint('payment_id'),
    sa.UniqueConstraint('token')
    )
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donation_created_at'), ['created_at'], unique=False)

    op.create_table('email_job',
    sa.Column('recipient', sa.String(length=254), nullable=False),
    sa.Column('subject', sa.String(length=180), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('email_job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_email_job_created_at'), ['created_at'], unique=False)

    op.create_table('event',
    sa.Column('location', sa.String(length=180), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('registration_enabled', sa.Boolean(), nullable=True),
    sa.Column('registration_limit', sa.Integer(), nullable=True),
    sa.Column('registration_count', sa.Integer(), nullable=False),
    sa.Column('organizer', sa.String(length=180), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=1000), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('seo_title', sa.String(length=180), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('registration_count >= 0'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_slug'), ['slug'], unique=True)

    op.create_table('faq',
    sa.Column('question', sa.String(length=250), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faq_created_at'), ['created_at'], unique=False)

    op.create_table('impact_statistic',
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('verified', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('value >= 0'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impact_statistic', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impact_statistic_created_at'), ['created_at'], unique=False)

    op.create_table('impact_story',
    sa.Column('date_label', sa.String(length=80), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=1000), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('seo_title', sa.String(length=180), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('impact_story', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_impact_story_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_impact_story_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_impact_story_slug'), ['slug'], unique=True)

    op.create_table('media_asset',
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('public_id', sa.String(length=255), nullable=True),
    sa.Column('secure_url', sa.String(length=1000), nullable=False),
    sa.Column('resource_type', sa.String(length=30), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(length=20), nullable=True),
    sa.Column('folder', sa.String(length=120), nullable=True),
    sa.Column('tags', sa.String(length=500), nullable=True),
    sa.Column('alt_text', sa.String(length=250), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('media_asset', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_media_asset_created_at'), ['created_at'], unique=False)

    op.create_table('navigation_item',
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('path', sa.String(length=180), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('navigation_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_navigation_item_created_at'), ['created_at'], unique=False)

    op.create_table('newsletter_subscriber',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('unsubscribe_token', sa.String(length=64), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('unsubscribe_token')
    )
    with op.batch_alter_table('newsletter_subscriber', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_newsletter_subscriber_created_at'), ['created_at'], unique=False)

    op.create_table('organization_setting',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('organization_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_setting_created_at'), ['created_at'], unique=False)

    op.create_table('page',
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=1000), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('seo_title', sa.String(length=180), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_page_slug'), ['slug'], unique=True)

    op.create_table('permission',
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_permission_created_at'), ['created_at'], unique=False)

    op.create_table('project_category',
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('project_category', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_category_created_at'), ['created_at'], unique=False)

    op.create_table('role',
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_role_created_at'), ['created_at'], unique=False)

    op.create_table('site_setting',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    with op.batch_alter_table('site_setting', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_site_setting_created_at'), ['created_at'], unique=False)

    op.create_table('social_link',
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    with op.batch_alter_table('social_link', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_social_link_created_at'), ['created_at'], unique=False)

    op.create_table('artisan',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=180), nullable=True),
    sa.Column('skill', sa.String(length=180), nullable=True),
    sa.Column('craft', sa.String(length=180), nullable=True),
    sa.Column('experience', sa.String(length=180), nullable=True),
    sa.Column('products', sa.Text(), nullable=True),
    sa.Column('social_url', sa.String(length=1000), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=1000), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('seo_title', sa.String(length=180), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['artisan_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('artisan', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_artisan_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_artisan_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_artisan_slug'), ['slug'], unique=True)

    op.create_table('blog_post',
    sa.Column('author', sa.String(length=120), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('publish_date', sa.Date(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=1000), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('seo_title', sa.String(length=180), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['blog_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blog_post_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_post_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_blog_post_slug'), ['slug'], unique=True)

    op.create_table('donation_receipt',
    sa.Column('donation_id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=80), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['donation_id'], ['donation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('donation_id'),
    sa.UniqueConstraint('receipt_number')
    )
    with op.batch_alter_table('donation_receipt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_donation_receipt_created_at'), ['created_at'], unique=False)

    op.create_table('event_registration',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'email')
    )
    with op.batch_alter_table('event_registration', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_registration_created_at'), ['created_at'], unique=False)

    op.create_table('page_section',
    sa.Column('page_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['page.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('page_section', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_page_section_created_at'), ['created_at'], unique=False)

    op.create_table('project',
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=180), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('beneficiary_count', sa.Integer(), nullable=False),
    sa.Column('target', sa.Integer(), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('activities', sa.Text(), nullable=True),
    sa.Column('outcomes', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('video', sa.String(length=1000), nullable=True),
    sa.Column('featured', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=1000), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('seo_title', sa.String(length=180), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('beneficiary_count >= 0'),
    sa.CheckConstraint('progress >= 0 AND progress <= 100'),
    sa.ForeignKeyConstraint(['category_id'], ['project_category.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_slug'), ['slug'], unique=True)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user',
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('failed_logins', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('volunteer_application',
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('occupation', sa.String(length=180), nullable=True),
    sa.Column('skills', sa.Text(), nullable=False),
    sa.Column('availability', sa.String(length=180), nullable=False),
    sa.Column('areas_of_interest', sa.String(length=500), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('resume_id', sa.Integer(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['media_asset.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('volunteer_application', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_application_created_at'), ['created_at'], unique=False)

    op.create_table('audit_log',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('entity', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    op.create_table('blog_tags',
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['blog_post.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['blog_tag.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'tag_id')
    )
    op.create_table('document',
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_asset.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_document_created_at'), ['created_at'], unique=False)

    op.create_table('gallery',
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('media_id', sa.Integer(), nullable=True),
    sa.Column('artisan_id', sa.Integer(), nullable=True),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=180), nullable=True),
    sa.Column('title', sa.String(length=180), nullable=False),
    sa.Column('slug', sa.String(length=180), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cover_image', sa.String(length=1000), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('seo_title', sa.String(length=180), nullable=True),
    sa.Column('seo_description', sa.String(length=320), nullable=True),
    sa.Column('keywords', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artisan_id'], ['artisan.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['media_id'], ['media_asset.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gallery_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_gallery_published'), ['published'], unique=False)
        batch_op.create_index(batch_op.f('ix_gallery_slug'), ['slug'], unique=True)

    op.create_table('project_image',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('media_id', sa.Integer(), nullable=False),
    sa.Column('caption', sa.String(length=250), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['media_asset.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_image_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_image_created_at'))

    op.drop_table('project_image')
    with op.batch_alter_table('gallery', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gallery_slug'))
        batch_op.drop_index(batch_op.f('ix_gallery_published'))
        batch_op.drop_index(batch_op.f('ix_gallery_created_at'))

    op.drop_table('gallery')
    with op.batch_alter_table('document', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_document_created_at'))

    op.drop_table('document')
    op.drop_table('blog_tags')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    op.drop_table('audit_log')
    with op.batch_alter_table('volunteer_application', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_application_created_at'))

    op.drop_table('volunteer_application')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))

    op.drop_table('user')
    op.drop_table('role_permissions')
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_slug'))
        batch_op.drop_index(batch_op.f('ix_project_published'))
        batch_op.drop_index(batch_op.f('ix_project_created_at'))

    op.drop_table('project')
    with op.batch_alter_table('page_section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_section_created_at'))

    op.drop_table('page_section')
    with op.batch_alter_table('event_registration', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_registration_created_at'))

    op.drop_table('event_registration')
    with op.batch_alter_table('donation_receipt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donation_receipt_created_at'))

    op.drop_table('donation_receipt')
    with op.batch_alter_table('blog_post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_post_slug'))
        batch_op.drop_index(batch_op.f('ix_blog_post_published'))
        batch_op.drop_index(batch_op.f('ix_blog_post_created_at'))

    op.drop_table('blog_post')
    with op.batch_alter_table('artisan', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artisan_slug'))
        batch_op.drop_index(batch_op.f('ix_artisan_published'))
        batch_op.drop_index(batch_op.f('ix_artisan_created_at'))

    op.drop_table('artisan')
    with op.batch_alter_table('social_link', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_social_link_created_at'))

    op.drop_table('social_link')
    with op.batch_alter_table('site_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_site_setting_created_at'))

    op.drop_table('site_setting')
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_role_created_at'))

    op.drop_table('role')
    with op.batch_alter_table('project_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_category_created_at'))

    op.drop_table('project_category')
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_permission_created_at'))

    op.drop_table('permission')
    with op.batch_alter_table('page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_page_slug'))
        batch_op.drop_index(batch_op.f('ix_page_published'))
        batch_op.drop_index(batch_op.f('ix_page_created_at'))

    op.drop_table('page')
    with op.batch_alter_table('organization_setting', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_setting_created_at'))

    op.drop_table('organization_setting')
    with op.batch_alter_table('newsletter_subscriber', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_newsletter_subscriber_created_at'))

    op.drop_table('newsletter_subscriber')
    with op.batch_alter_table('navigation_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_navigation_item_created_at'))

    op.drop_table('navigation_item')
    with op.batch_alter_table('media_asset', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_media_asset_created_at'))

    op.drop_table('media_asset')
    with op.batch_alter_table('impact_story', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impact_story_slug'))
        batch_op.drop_index(batch_op.f('ix_impact_story_published'))
        batch_op.drop_index(batch_op.f('ix_impact_story_created_at'))

    op.drop_table('impact_story')
    with op.batch_alter_table('impact_statistic', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_impact_statistic_created_at'))

    op.drop_table('impact_statistic')
    with op.batch_alter_table('faq', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faq_created_at'))

    op.drop_table('faq')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_slug'))
        batch_op.drop_index(batch_op.f('ix_event_published'))
        batch_op.drop_index(batch_op.f('ix_event_created_at'))

    op.drop_table('event')
    with op.batch_alter_table('email_job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_email_job_created_at'))

    op.drop_table('email_job')
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_donation_created_at'))

    op.drop_table('donation')
    with op.batch_alter_table('contact_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_contact_message_created_at'))

    op.drop_table('contact_message')
    with op.batch_alter_table('blog_tag', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_tag_created_at'))

    op.drop_table('blog_tag')
    with op.batch_alter_table('blog_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blog_category_created_at'))

    op.drop_table('blog_category')
    with op.batch_alter_table('artisan_category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_artisan_category_created_at'))

    op.drop_table('artisan_category')
    # ### end Alembic commands ###
